apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-2
spec:
  template:
    spec:
      containers:
      - name: demo
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          items:
          - key: the-thing
            path: another-thing
          name: demo
        name: config
