apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  component: example-2
resources:
  - ../base

patches:
  - target:
      kind: Deployment
      name: example
    patch: |-
      - op: replace
        path: /metadata/name
        value: example-2

  - path: deploy.yaml
