apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-1
spec:
  template:
    spec:
      containers:
        - name: demo
          volumeMounts:
          - mountPath: /config
            name: config
