apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-3
spec:
  template:
    spec:
      containers:
      - name: demo
        volumeMounts:
        - mountPath: /etc/the-thing
          name: config
          subPath: the-thing
